kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: vinroute 
  namespace: mq 
spec:
  host: tlsconn.chl.mq.ibm.com
  to:
    kind: Service
    name: vin-ibm-mq 
  port:
    targetPort: 1416
  tls:
    termination: passthrough
